services:
  - type: web
    name: face-health-digital-twin
    runtime: docker
    plan: starter
    region: oregon

    dockerfilePath: ./Dockerfile

    healthCheckPath: /health

    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: LIBGL_ALWAYS_SOFTWARE
        value: "1"
      - key: MESA_GL_VERSION_OVERRIDE
        value: "3.3"
      - key: EGL_PLATFORM
        value: "surfaceless"

    autoDeploy: true
